# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["isaacsim[all,extscache]==6.0.1.0", "pip"]
# [tool.uv]
# extra-index-url = ["https://pypi.nvidia.com"]
# index-strategy = "unsafe-best-match"
# prerelease = "allow"
# ///
"""Layer 1: can the robot tell what it is standing on, from proprioception alone?

This is the piece that separates "we widened a domain-randomisation range" (a
config change) from a system that KNOWS the surface it is on and can report it.
It is also what the 340-byte Iridium telemetry packet would carry.

Why offline regression instead of teacher-student RL
----------------------------------------------------
COLA (arXiv 2510.14293) trains a privileged teacher and distils it into a
proprioception-only student -- correct, and expensive. But the estimator does not
have to be learned jointly with the policy: friction is a property of the episode,
not of the action. So roll the FIXED ice policy across randomised friction, log
(observation history -> true mu) pairs, and fit a regressor. Supervised, one pass,
minutes of GPU rather than hours.

The honest test is generalisation to friction values held out of training, which
is what the log at the end reports.

What the policy can actually see
--------------------------------
Only the 123-dim policy observation -- joint positions, joint velocities, previous
actions, IMU. NOT contact forces or foot velocities: those are privileged in Isaac
Lab and absent on real hardware. COLA's insight is that the offset between a joint's
commanded and achieved position is a proxy for the force it met, which is exactly
the signal a slipping foot leaves in proprioception. A history window is required
because friction is not observable from one frame.

Run:
  hf jobs uv run --detach --namespace iteratehack --flavor l4x1 --timeout 60m \
      --env OMNI_KIT_ACCEPT_EULA=YES \
      -v hf://buckets/iteratehack/jobs-artifacts:/mnt \
      --label name=himalaya-traction --label task=estimate-mu \
      estimate_mu.py
"""

import json
import os
import pathlib
import subprocess
import sys
import textwrap

os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
os.environ.setdefault("HOME", "/root")

PY = sys.executable
LAB = "/tmp/IsaacLab"
BUCKET = pathlib.Path("/mnt/himalaya-g1")
POLICY = BUCKET / "ice-isaac/rsl_rl/g1_flat/2026-08-29_21-48-51/exported/policy.pt"


def sh(cmd, timeout, label, tail=12):
    print(f"\n$ {cmd}", flush=True)
    p = subprocess.run(cmd, shell=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print("\n".join(p.stdout.splitlines()[-tail:]), flush=True)
    return p.returncode == 0


sh("apt-get update -qq && apt-get install -y -qq --no-install-recommends "
   "libgl1 libglu1-mesa libegl1 libvulkan1 libxrandr2 libxinerama1 libxcursor1 "
   "libxi6 libsm6 libice6 libxt6 libgomp1 git && echo apt-ok", 900, "apt", tail=2)
sh(f"git clone --depth 1 -q https://github.com/isaac-sim/IsaacLab.git {LAB} && echo cloned",
   900, "clone", tail=2)
for pkg in ["isaaclab", "isaaclab_ov", "isaaclab_physx", "isaaclab_ovphysx",
            "isaaclab_newton", "isaaclab_assets", "isaaclab_rl", "isaaclab_tasks",
            "isaaclab_visualizers"]:
    sh(f"{PY} -m pip install --no-cache-dir -e {LAB}/source/{pkg} 2>&1 | tail -1",
       1200, f"install {pkg}", tail=1)
sh(f"{PY} -m pip install --no-cache-dir rsl-rl-lib 2>&1 | tail -1", 600, "rsl_rl", tail=1)

# Training env: the ice env, so friction is randomised per episode across the range.
G1DIR = pathlib.Path(f"{LAB}/source/isaaclab_tasks/isaaclab_tasks/manager_based/"
                     f"locomotion/velocity/config/g1")
(G1DIR / "mu_env_cfg.py").write_text(textwrap.dedent('''
    """Ice env for mu-estimation data collection. Generated by estimate_mu.py."""
    from isaaclab.utils.configclass import configclass
    from .flat_env_cfg import G1FlatEnvCfg


    @configclass
    class G1MuEnvCfg(G1FlatEnvCfg):
        def __post_init__(self):
            super().__post_init__()
            self.events.physics_material.params["static_friction_range"] = (0.05, 1.0)
            self.events.physics_material.params["dynamic_friction_range"] = (0.04, 0.9)
            self.rewards.feet_slide.weight = -0.01
            # Clean signal: the estimator should learn friction, not observation
            # noise, and pushes would inject forces unrelated to the surface.
            self.observations.policy.enable_corruption = False
            self.events.push_robot = None
            # Keep them walking so there is gait to read friction from. A standing
            # robot leaves almost no signal in proprioception.
            self.commands.base_velocity.ranges.lin_vel_x = (0.6, 0.6)
            self.commands.base_velocity.ranges.lin_vel_y = (0.0, 0.0)
            self.commands.base_velocity.ranges.ang_vel_z = (0.0, 0.0)
            self.commands.base_velocity.resampling_time_range = (1e6, 1e6)
'''))
with open(G1DIR / "__init__.py", "a") as f:
    f.write(textwrap.dedent('''

        import gymnasium as gym  # noqa: E402
        from . import agents  # noqa: E402
        gym.register(
            id="Isaac-Mu-G1-v0",
            entry_point="isaaclab.envs:ManagerBasedRLEnv",
            disable_env_checker=True,
            kwargs={"env_cfg_entry_point": f"{__name__}.mu_env_cfg:G1MuEnvCfg",
                    "rsl_rl_cfg_entry_point":
                        f"{agents.__name__}.rsl_rl_ppo_cfg:G1FlatPPORunnerCfg"},
        )
    '''))

MU = textwrap.dedent(f'''
    import json, os, pathlib
    os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
    os.environ.setdefault("HOME", "/root")
    from isaaclab.app import AppLauncher
    app = AppLauncher(headless=True, device="cuda:0").app

    import gymnasium as gym, torch, torch.nn as nn, numpy as np
    import isaaclab_tasks  # noqa
    from isaaclab_tasks.utils import parse_env_cfg

    DEV = "cuda:0"
    N_ENVS, WARMUP, COLLECT = 512, 60, 260
    HIST = 25                      # COLA ablated 10/25/50 and chose 25
    OUT = pathlib.Path("/mnt/himalaya-g1/mu_estimator"); OUT.mkdir(parents=True, exist_ok=True)

    policy = torch.jit.load("{POLICY}").to(DEV).eval()
    cfg = parse_env_cfg("Isaac-Mu-G1-v0", device=DEV, num_envs=N_ENVS)
    env = gym.make("Isaac-Mu-G1-v0", cfg=cfg)
    obs_d, _ = env.reset()
    obs = obs_d["policy"]
    OBS_D = obs.shape[-1]
    print(f"obs dim {{OBS_D}}, {{N_ENVS}} envs, history {{HIST}}", flush=True)

    # Ground truth: the friction PhysX actually applied this episode. Material
    # tensor is [num_envs, num_shapes, 3] = (static, dynamic, restitution).
    view = env.unwrapped.scene["robot"].root_physx_view
    mats = torch.as_tensor(np.asarray(view.get_material_properties()), device=DEV)
    mu_true = mats[:, 0, 0].clone()
    print(f"true mu: min {{mu_true.min():.3f}} max {{mu_true.max():.3f}} "
          f"mean {{mu_true.mean():.3f}}", flush=True)

    ring = torch.zeros(N_ENVS, HIST, OBS_D, device=DEV)
    X, Y = [], []
    with torch.inference_mode():
        for step in range(WARMUP + COLLECT):
            act = policy(obs)
            obs_d, _, term, trunc, _ = env.step(act)
            obs = obs_d["policy"]
            ring = torch.roll(ring, -1, dims=1); ring[:, -1] = obs
            # Skip envs that reset this step: their history straddles two episodes
            # (and two friction draws), so those windows are mislabelled.
            fresh = ~(term.bool() | trunc.bool())
            if step >= WARMUP and step % 3 == 0:
                X.append(ring[fresh].reshape(int(fresh.sum()), -1).cpu())
                Y.append(mu_true[fresh].cpu())
    env.close()

    X = torch.cat(X); Y = torch.cat(Y)
    print(f"dataset: {{tuple(X.shape)}} -> {{tuple(Y.shape)}}", flush=True)

    # Held-out by FRICTION VALUE, not at random: a random split leaks, because
    # windows from the same episode share a label and would appear on both sides.
    # Generalising to unseen mu is the claim worth making.
    lo, hi = torch.quantile(Y, torch.tensor([0.35, 0.65]))
    test_mask = (Y >= lo) & (Y <= hi)          # hold out the MIDDLE band
    Xtr, Ytr = X[~test_mask].to(DEV), Y[~test_mask].to(DEV)
    Xte, Yte = X[test_mask].to(DEV), Y[test_mask].to(DEV)
    print(f"train {{len(Xtr)}} (mu outside [{{lo:.2f}},{{hi:.2f}}]) / "
          f"test {{len(Xte)}} (inside)", flush=True)

    mean, std = Xtr.mean(0, keepdim=True), Xtr.std(0, keepdim=True) + 1e-6
    # Predict log mu: the range spans 20x and relative error is what matters.
    ytr, yte = torch.log(Ytr), torch.log(Yte)

    net = nn.Sequential(nn.Linear(X.shape[1], 512), nn.ELU(),
                        nn.Linear(512, 256), nn.ELU(),
                        nn.Linear(256, 1)).to(DEV)
    opt = torch.optim.AdamW(net.parameters(), lr=1e-3, weight_decay=1e-4)
    for ep in range(40):
        perm = torch.randperm(len(Xtr), device=DEV)
        tot = 0.0
        for i in range(0, len(perm), 4096):
            idx = perm[i:i+4096]
            loss = nn.functional.mse_loss(
                net((Xtr[idx] - mean) / std).squeeze(-1), ytr[idx])
            opt.zero_grad(); loss.backward(); opt.step()
            tot += loss.item() * len(idx)
        if ep % 10 == 9:
            with torch.no_grad():
                pt = net((Xte - mean) / std).squeeze(-1)
                r2 = 1 - ((pt - yte)**2).sum() / ((yte - yte.mean())**2).sum()
                print(f"  epoch {{ep+1:3d}}  train {{tot/len(Xtr):.4f}}  "
                      f"heldout R2 {{r2:.3f}}", flush=True)

    with torch.no_grad():
        pred = torch.exp(net((Xte - mean) / std).squeeze(-1))
        r2 = (1 - ((torch.log(pred) - yte)**2).sum()
                / ((yte - yte.mean())**2).sum()).item()
        rel = ((pred - Yte).abs() / Yte).mean().item()
        # Does it separate ice from rock at all? That is the operational question.
        is_ice = Yte < 0.15
        acc = ((pred < 0.15) == is_ice).float().mean().item() if is_ice.any() else float("nan")

    res = {{"held_out_R2_logmu": round(r2, 4),
           "mean_relative_error": round(rel, 4),
           "ice_vs_rock_accuracy": round(acc, 4),
           "history_len": HIST, "obs_dim": OBS_D,
           "n_train": len(Xtr), "n_test": len(Xte),
           "heldout_mu_band": [round(lo.item(), 3), round(hi.item(), 3)]}}
    print("\\n" + json.dumps(res, indent=2), flush=True)
    (OUT / "mu_estimator_results.json").write_text(json.dumps(res, indent=2))
    torch.save({{"state_dict": net.state_dict(), "mean": mean.cpu(), "std": std.cpu(),
                "hist": HIST, "obs_dim": OBS_D}}, OUT / "mu_estimator.pt")
    print("saved estimator ->", OUT / "mu_estimator.pt", flush=True)
    app.close()
''')
pathlib.Path("mu.py").write_text(MU)
sh(f"{PY} mu.py 2>&1 | grep -vE 'neuraylib|material_library|\\[Warning\\]' | tail -40",
   3000, "estimate mu", tail=40)
