# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["isaacsim[all,extscache]==6.0.1.0", "pip"]
# [tool.uv]
# extra-index-url = ["https://pypi.nvidia.com"]
# index-strategy = "unsafe-best-match"
# prerelease = "allow"
# ///
"""Export and film the ice+slope policy -- the mountain case.

Trained on Isaac Lab's ROUGH terrain (generated slopes, stairs, obstacles) with
friction spanning ice to rock, reaching 93.5% survival and 0.774 tracking. It is
the only policy here that has ever seen an incline, and it carries the height
scanner, so it can see terrain ahead rather than only feel the ground underfoot.

Two stages because the exported TorchScript does not exist yet:
  1. run play.py once against the checkpoint -- it writes exported/policy.pt NEXT
     TO THE CHECKPOINT (in the bucket), which is the detail that cost an earlier
     job when I searched IsaacLab/logs instead
  2. drive an explicit capture loop, since play.py --video records nothing

Filmed on the ROUGH terrain it was trained for, at two surfaces:
    snow  mu = 0.20   packed snow / neve -- what an approach march crosses
    ice   mu = 0.12   hard glacial ice

mu = 0.06 (bare wet ice) is deliberately NOT filmed as a headline: it is near the
physical limit for a legged system -- humans need crampons -- so a robot falling
there is physics, not a policy failure.

Run:
  hf jobs uv run --detach --namespace iteratehack --flavor l40sx1 --timeout 50m \
      --env OMNI_KIT_ACCEPT_EULA=YES \
      -v hf://buckets/iteratehack/jobs-artifacts:/mnt \
      --label name=himalaya-traction --label task=film-slope \
      film_slope.py
"""

import json
import os
import pathlib
import subprocess
import sys
import textwrap

os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
os.environ.setdefault("HOME", "/root")

PY = sys.executable
LAB = "/tmp/IsaacLab"
BUCKET = pathlib.Path("/mnt/himalaya-g1")
CKPT = BUCKET / "ice-slope/rsl_rl/g1_rough/2026-08-30_00-58-20/model_2999.pt"
EXPORTED = CKPT.parent / "exported" / "policy.pt"


def sh(cmd, timeout, label, tail=12):
    """Never let one slow step kill the job.

    The first run of this script died with TimeoutExpired propagating out of the
    export stage: rough-terrain generation plus Isaac Sim startup exceeded the cap,
    and because subprocess.run was not wrapped, a slow step became a fatal one.
    Record the timeout and carry on -- the caller decides whether it was fatal.
    """
    print(f"\n$ {cmd}", flush=True)
    try:
        p = subprocess.run(cmd, shell=True, timeout=timeout,
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        print("\n".join(p.stdout.splitlines()[-tail:]), flush=True)
        return p.returncode == 0
    except subprocess.TimeoutExpired:
        print(f"[{label}] TIMEOUT after {timeout}s -- continuing", flush=True)
        return False


sh("apt-get update -qq && apt-get install -y -qq --no-install-recommends "
   "libgl1 libglu1-mesa libegl1 libvulkan1 libxrandr2 libxinerama1 libxcursor1 "
   "libxi6 libsm6 libice6 libxt6 libgomp1 git ffmpeg && echo apt-ok", 900, "apt", tail=2)
sh(f"git clone --depth 1 -q https://github.com/isaac-sim/IsaacLab.git {LAB} && echo cloned",
   900, "clone", tail=2)
for pkg in ["isaaclab", "isaaclab_ov", "isaaclab_physx", "isaaclab_ovphysx",
            "isaaclab_newton", "isaaclab_assets", "isaaclab_rl", "isaaclab_tasks",
            "isaaclab_visualizers", "isaaclab_contrib"]:
    sh(f"{PY} -m pip install --no-cache-dir -e {LAB}/source/{pkg} 2>&1 | tail -1",
       1200, f"install {pkg}", tail=1)
sh(f"{PY} -m pip install --no-cache-dir rsl-rl-lib imageio imageio-ffmpeg 2>&1 | tail -1",
   600, "deps", tail=1)

# Re-register the ice-slope env: each job re-clones Isaac Lab, so registration from
# the training job does not persist. Same class the policy was trained on, plus
# filming variants at two friction levels.
G1DIR = pathlib.Path(f"{LAB}/source/isaaclab_tasks/isaaclab_tasks/manager_based/"
                     f"locomotion/velocity/config/g1")
(G1DIR / "slopefilm_env_cfg.py").write_text(textwrap.dedent('''
    """Slope terrain at walkable winter frictions. Generated by film_slope.py."""
    from isaaclab.utils.configclass import configclass
    import isaaclab.terrains as terrain_gen
    from isaaclab.terrains import TerrainGeneratorCfg
    from .rough_env_cfg import G1RoughEnvCfg

    # A clean incline, not the stock rough mix. The default generator produces
    # blocks and stairs, which is why the first slope clips showed terrain and no
    # robot -- it was behind them.
    PURE_SLOPE = TerrainGeneratorCfg(
        size=(10.0, 10.0), border_width=15.0, num_rows=2, num_cols=2,
        horizontal_scale=0.1, vertical_scale=0.005, slope_threshold=0.75,
        use_cache=True,
        sub_terrains={"slope": terrain_gen.HfPyramidSlopedTerrainCfg(
            proportion=1.0, slope_range=(0.20, 0.30),
            platform_width=3.0, border_width=0.5)},
    )


    class _Base(G1RoughEnvCfg):
        def __post_init__(self):
            super().__post_init__()
            # Generating rough terrain is what blew the export timeout the first
            # time. Cache it so the second env build reuses the first one's mesh.
            self.scene.terrain.terrain_type = "generator"
            self.scene.terrain.terrain_generator = PURE_SLOPE
            self.rewards.feet_slide.weight = -0.01
            self.observations.policy.enable_corruption = False
            self.events.push_robot = None
            self.events.base_external_force_torque = None
            # One robot: on generated terrain the camera anchors to an env origin,
            # and with several the subject ends up a speck on a distant tile.
            self.scene.num_envs = 1
            # Steady forward march rather than resampled commands.
            self.commands.base_velocity.ranges.lin_vel_x = (0.7, 0.7)
            self.commands.base_velocity.ranges.lin_vel_y = (0.0, 0.0)
            self.commands.base_velocity.ranges.ang_vel_z = (0.0, 0.0)
            self.commands.base_velocity.resampling_time_range = (1e6, 1e6)


    @configclass
    class G1SlopeSnowCfg(_Base):
        def __post_init__(self):
            super().__post_init__()
            self.events.physics_material.params["static_friction_range"] = (0.20, 0.20)
            self.events.physics_material.params["dynamic_friction_range"] = (0.16, 0.16)


    @configclass
    class G1SlopeIceCfg(_Base):
        def __post_init__(self):
            super().__post_init__()
            self.events.physics_material.params["static_friction_range"] = (0.12, 0.12)
            self.events.physics_material.params["dynamic_friction_range"] = (0.10, 0.10)


    # Training config, needed by play.py to export the policy.
    @configclass
    class G1IceSlopeEnvCfg(G1RoughEnvCfg):
        def __post_init__(self):
            super().__post_init__()
            self.events.physics_material.params["static_friction_range"] = (0.05, 1.0)
            self.events.physics_material.params["dynamic_friction_range"] = (0.04, 0.9)
            self.rewards.feet_slide.weight = -0.01
'''))
with open(G1DIR / "__init__.py", "a") as f:
    f.write(textwrap.dedent('''

        import gymnasium as gym  # noqa: E402
        from . import agents  # noqa: E402
        for _id, _cls in [("Isaac-Velocity-Rough-G1-Ice-v0", "G1IceSlopeEnvCfg"),
                          ("Isaac-SlopeFilm-G1-Snow-v0", "G1SlopeSnowCfg"),
                          ("Isaac-SlopeFilm-G1-Ice-v0", "G1SlopeIceCfg")]:
            gym.register(
                id=_id,
                entry_point="isaaclab.envs:ManagerBasedRLEnv",
                disable_env_checker=True,
                kwargs={"env_cfg_entry_point": f"{__name__}.slopefilm_env_cfg:{_cls}",
                        "rsl_rl_cfg_entry_point":
                            f"{agents.__name__}.rsl_rl_ppo_cfg:G1RoughPPORunnerCfg"},
            )
    '''))

# ---- stage 1: export TorchScript, if it is not already there --------------------
if not EXPORTED.exists():
    play_py = subprocess.run(f"find {LAB} -path '*rsl_rl*' -name play.py | head -1",
                             shell=True, capture_output=True, text=True).stdout.strip()
    print("\n=== exporting slope policy ===", flush=True)
    sh(f"cd {LAB} && {PY} {play_py} --task Isaac-Velocity-Rough-G1-Ice-v0 "
       f"--checkpoint {CKPT} --num_envs 2 --headless 2>&1 "
       "| grep -viE 'neuraylib|material_library|warning' | tail -6", 3000, "export", tail=6)
print("exported exists:", EXPORTED.exists(), flush=True)
if not EXPORTED.exists():
    sys.exit("export did not produce policy.pt -- nothing to film. Check whether "
             "play.py timed out during terrain generation.")

# ---- stage 2: film -------------------------------------------------------------
FILM = textwrap.dedent(f'''
    import json, os, pathlib
    os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
    os.environ.setdefault("HOME", "/root")
    from isaaclab.app import AppLauncher
    app = AppLauncher(headless=True, enable_cameras=True, device="cuda:0").app

    import gymnasium as gym, torch, imageio, numpy as np
    import isaaclab_tasks  # noqa
    from isaaclab_tasks.utils import parse_env_cfg

    OUT = pathlib.Path("/mnt/himalaya-g1/videos"); OUT.mkdir(parents=True, exist_ok=True)
    STEPS = 1500
    policy = torch.jit.load("{EXPORTED}").to("cuda:0").eval()

    report = {{}}
    for tag, task in [("slope_snow", "Isaac-SlopeFilm-G1-Snow-v0"),
                      ("slope_ice",  "Isaac-SlopeFilm-G1-Ice-v0")]:
        print(f"\\n=== {{tag}} ===", flush=True)
        try:
            cfg = parse_env_cfg(task, device="cuda:0", num_envs=1)
            cfg.viewer.origin_type = "asset_root"
            cfg.viewer.asset_name = "robot"
            cfg.viewer.env_index = 0
            cfg.viewer.eye = (4.5, 4.5, 3.0)     # back and well above the relief
            cfg.viewer.lookat = (0.0, 0.0, 0.8)
            cfg.viewer.resolution = (960, 540)
            env = gym.make(task, cfg=cfg, render_mode="rgb_array")
            obs_d, _ = env.reset(); obs = obs_d["policy"]
            frames, falls = [], 0.0
            with torch.inference_mode():
                for i in range(STEPS):
                    obs_d, _, term, trunc, _ = env.step(policy(obs))
                    obs = obs_d["policy"]
                    falls += float(term.float().sum().item())
                    if i %  2 == 0:
                        f = env.unwrapped.render()
                        if f is not None:
                            frames.append(np.asarray(f))
            env.close()
            if frames:
                p = OUT / f"slope_{{tag}}.mp4"
                imageio.mimwrite(p, frames, fps=25, quality=8, macro_block_size=1)
                report[tag] = {{"falls": falls, "steps": STEPS,
                               "steps_between_falls": round(STEPS/(falls+1e-9), 1)
                                                      if falls else STEPS,
                               "file": str(p)}}
                print(f"WROTE {{p}} {{len(frames)}} frames, {{falls:.0f}} falls "
                      f"= 1 per {{STEPS/(falls+1e-9) if falls else STEPS:.0f}} steps",
                      flush=True)
            else:
                report[tag] = {{"error": "no frames"}}
        except Exception as e:
            import traceback; traceback.print_exc(); report[tag] = {{"error": repr(e)}}

    (OUT / "slope_film_report.json").write_text(json.dumps(report, indent=2))
    print("\\n" + json.dumps(report, indent=2), flush=True)
    app.close()
''')
pathlib.Path("sfilm.py").write_text(FILM)
sh(f"{PY} sfilm.py 2>&1 | grep -vE 'neuraylib|material_library|\\[Warning\\]' | tail -30",
   2400, "film slope", tail=30)
