# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["isaacsim[all,extscache]==6.0.1.0", "pip"]
# [tool.uv]
# extra-index-url = ["https://pypi.nvidia.com"]
# index-strategy = "unsafe-best-match"
# prerelease = "allow"
# ///
"""Render the trained Isaac policies to mp4 so they can actually be watched.

Isaac Sim needs an NVIDIA GPU, so this cannot run on a Mac -- it renders headless
here and drops the videos in the bucket to download.

Records four clips, which together ARE the demo:

    baseline on ROCK   the stock policy doing what it was trained for
    baseline on ICE    the failure this whole project is about
    ice      on ICE    the fix
    ice      on ROCK   proof the fix did not cost anything on normal ground

Friction is pinned to a POINT per surface (not a range) so the two policies are
filmed on identical ground and the clips are honestly comparable.

Note: each job re-clones Isaac Lab, so the env registration must be re-injected
here -- it does not persist from the training job.

Run:
  hf jobs uv run --detach --namespace iteratehack --flavor l4x1 --timeout 50m \
      --env OMNI_KIT_ACCEPT_EULA=YES \
      -v hf://buckets/iteratehack/jobs-artifacts:/mnt \
      --label name=himalaya-traction --label task=play-video \
      play_isaac.py
"""

import os
import pathlib
import subprocess
import sys
import textwrap

os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
os.environ.setdefault("HOME", "/root")

PY = sys.executable
LAB = "/tmp/IsaacLab"
BUCKET = pathlib.Path("/mnt/himalaya-g1")
OUT = BUCKET / "videos"

POLICIES = {
    "baseline": BUCKET / "baseline/rsl_rl/g1_flat/2026-08-29_20-54-12/model_1499.pt",
    "ice": BUCKET / "ice-isaac/rsl_rl/g1_flat/2026-08-29_21-48-51/model_1499.pt",
}
SURFACES = {"rock": "Isaac-Play-G1-Rock-v0", "ice": "Isaac-Play-G1-Ice-v0"}
VIDEO_LEN = 500


def sh(cmd, timeout, label, tail=12):
    print(f"\n$ {cmd}", flush=True)
    p = subprocess.run(cmd, shell=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print("\n".join(p.stdout.splitlines()[-tail:]), flush=True)
    return p.returncode == 0


sh("apt-get update -qq && apt-get install -y -qq --no-install-recommends "
   "libgl1 libglu1-mesa libegl1 libvulkan1 libxrandr2 libxinerama1 libxcursor1 "
   "libxi6 libsm6 libice6 libxt6 libgomp1 git ffmpeg && echo apt-ok", 900, "apt", tail=2)
sh(f"git clone --depth 1 -q https://github.com/isaac-sim/IsaacLab.git {LAB} && echo cloned",
   900, "clone", tail=2)
for pkg in ["isaaclab", "isaaclab_ov", "isaaclab_physx", "isaaclab_ovphysx",
            "isaaclab_newton", "isaaclab_assets", "isaaclab_rl", "isaaclab_tasks",
            "isaaclab_visualizers"]:
    sh(f"{PY} -m pip install --no-cache-dir -e {LAB}/source/{pkg} 2>&1 | tail -1",
       1200, f"install {pkg}", tail=1)
sh(f"{PY} -m pip install --no-cache-dir rsl-rl-lib 2>&1 | tail -1", 600, "rsl_rl", tail=1)

G1DIR = pathlib.Path(f"{LAB}/source/isaaclab_tasks/isaaclab_tasks/manager_based/"
                     f"locomotion/velocity/config/g1")
(G1DIR / "play_env_cfg.py").write_text(textwrap.dedent('''
    """Fixed-friction play variants for filming. Generated by play_isaac.py."""
    from isaaclab.utils.configclass import configclass
    from .flat_env_cfg import G1FlatEnvCfg


    class _PlayBase(G1FlatEnvCfg):
        def __post_init__(self):
            super().__post_init__()
            # Few envs so the camera frames one robot, and no corruption/pushes so
            # what is on screen is the policy, not the disturbance generator.
            self.scene.num_envs = 9
            self.scene.env_spacing = 2.5
            self.observations.policy.enable_corruption = False
            self.events.push_robot = None
            self.events.base_external_force_torque = None


    @configclass
    class G1PlayRockCfg(_PlayBase):
        def __post_init__(self):
            super().__post_init__()
            self.events.physics_material.params["static_friction_range"] = (0.8, 0.8)
            self.events.physics_material.params["dynamic_friction_range"] = (0.6, 0.6)


    @configclass
    class G1PlayIceCfg(_PlayBase):
        def __post_init__(self):
            super().__post_init__()
            self.events.physics_material.params["static_friction_range"] = (0.08, 0.08)
            self.events.physics_material.params["dynamic_friction_range"] = (0.06, 0.06)
'''))

with open(G1DIR / "__init__.py", "a") as f:
    f.write(textwrap.dedent('''

        import gymnasium as gym  # noqa: E402
        from . import agents  # noqa: E402

        for _id, _cls in [("Isaac-Play-G1-Rock-v0", "G1PlayRockCfg"),
                          ("Isaac-Play-G1-Ice-v0", "G1PlayIceCfg")]:
            gym.register(
                id=_id,
                entry_point="isaaclab.envs:ManagerBasedRLEnv",
                disable_env_checker=True,
                kwargs={
                    "env_cfg_entry_point": f"{__name__}.play_env_cfg:{_cls}",
                    "rsl_rl_cfg_entry_point":
                        f"{agents.__name__}.rsl_rl_ppo_cfg:G1FlatPPORunnerCfg",
                },
            )
    '''))

play_py = subprocess.run(f"find {LAB} -path '*rsl_rl*' -name play.py | head -1",
                         shell=True, capture_output=True, text=True).stdout.strip()
print("play script:", play_py, flush=True)
OUT.mkdir(parents=True, exist_ok=True)

for pname, ckpt in POLICIES.items():
    if not pathlib.Path(ckpt).exists():
        print(f"!! missing checkpoint for {pname}: {ckpt}", flush=True)
        continue
    for sname, task in SURFACES.items():
        tag = f"{pname}_on_{sname}"
        print(f"\n{'='*60}\nRECORDING {tag}\n{'='*60}", flush=True)
        ok = sh(f"cd {LAB} && {PY} {play_py} --task {task} --checkpoint {ckpt} "
                f"--num_envs 9 --headless --video --video_length {VIDEO_LEN} "
                f"--enable_cameras 2>&1 "
                "| grep -vE 'neuraylib|material_library|\\[Warning\\]' | tail -20",
                1800, f"record {tag}", tail=20)
        # play.py writes into logs/rsl_rl/<exp>/<stamp>/videos/play/*.mp4
        sh(f"find {LAB}/logs -name '*.mp4' -newermt '-30 minutes' "
           f"-exec cp {{}} {OUT}/{tag}.mp4 \\; ; ls -la {OUT}/{tag}.mp4 2>/dev/null "
           f"|| echo 'NO VIDEO for {tag}'", 300, f"collect {tag}", tail=4)

sh(f"ls -la {OUT}", 120, "final videos", tail=10)
print("\nvideos -> hf://buckets/iteratehack/jobs-artifacts/himalaya-g1/videos/", flush=True)
