# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["isaacsim[all,extscache]==6.0.1.0", "pip"]
# [tool.uv]
# extra-index-url = ["https://pypi.nvidia.com"]
# index-strategy = "unsafe-best-match"
# prerelease = "allow"
# ///
"""Train the G1 on ICE in Isaac Lab -- the 'after' arm of the A/B.

The claim being tested, verified in-tree earlier today:
    velocity_env_cfg.py  static_friction_range=(0.8, 0.8)
                         dynamic_friction_range=(0.6, 0.6)
Min == max, so Isaac Lab's humanoid trains at ONE friction value and never
randomizes it (Spot's env in the same tree uses (0.3, 1.0) / (0.3, 0.8) -- the
quadruped gets randomization, the humanoid does not). Real ice is 0.05-0.15.

Why a config override rather than a custom event function:
  Introspection showed the articulation exposes a (num_envs, 3, 3) material tensor
  -- only THREE shapes -- so per-foot asymmetry is not cleanly reachable through
  this API the way it is in MuJoCo (ice_randomize.py sets pair_friction per foot).
  But the stock term already accepts ranges; Isaac just ships them collapsed to a
  point. Widening them is the whole experiment, and needs no new machinery.

  The refinements the MuJoCo track has -- log-uniform sampling (uniform over
  [0.05, 1.0] puts ~95% of mass above ice) and per-foot asymmetry -- are
  improvements on top of this, not prerequisites for it.

Two deltas from stock, both deliberate:
  1. friction ranges widened to span ice -> rock
  2. feet_slide penalty relaxed from -0.1 to -0.01

     (2) is NOT cosmetic. Sliding is physically unavoidable on ice, so a stiff
     feet_slide penalty punishes the policy for the surface rather than for its
     gait, and pushes it toward standing still. The stock baseline scored
     feet_slide = -0.0269 at mu=0.8, i.e. the term is near-inactive on grippy
     ground -- it only starts biting once the ground is slippery, which is
     exactly when we do not want it dominating.

Run:
  hf jobs uv run --detach --namespace iteratehack --flavor a100-large --timeout 90m \
      --env OMNI_KIT_ACCEPT_EULA=YES \
      -v hf://buckets/iteratehack/jobs-artifacts:/mnt \
      --label name=himalaya-traction --label task=train-ice-isaac \
      train_ice_isaac.py
"""

import os
import pathlib
import subprocess
import sys
import textwrap
import time

os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
os.environ.setdefault("HOME", "/root")

PY = sys.executable
LAB = "/tmp/IsaacLab"
OUT = pathlib.Path("/mnt/himalaya-g1/ice-isaac")
TASK = "Isaac-Velocity-Flat-G1-Ice-v0"
NUM_ENVS = 4096
MAX_ITER = 1500

# Ice is ~0.05-0.15, dry rock ~1.0. Spanning the whole way keeps the policy able to
# walk normally when the ground IS grippy -- an ice-only policy would be useless.
ICE_STATIC = (0.05, 1.0)
ICE_DYNAMIC = (0.04, 0.9)


def sh(cmd, timeout, label, tail=15):
    print(f"\n$ {cmd}", flush=True)
    t0 = time.time()
    p = subprocess.run(cmd, shell=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print("\n".join(p.stdout.splitlines()[-tail:]), flush=True)
    print(f"[{label}] rc={p.returncode} in {time.time()-t0:.0f}s", flush=True)
    return p.returncode == 0


sh("apt-get update -qq && apt-get install -y -qq --no-install-recommends "
   "libgl1 libglu1-mesa libegl1 libvulkan1 libxrandr2 libxinerama1 libxcursor1 "
   "libxi6 libsm6 libice6 libxt6 libgomp1 git ffmpeg && echo apt-ok", 900, "apt", tail=2)
sh(f"git clone --depth 1 -q https://github.com/isaac-sim/IsaacLab.git {LAB} && echo cloned",
   900, "clone", tail=2)
for pkg in ["isaaclab", "isaaclab_ov", "isaaclab_physx", "isaaclab_ovphysx",
            "isaaclab_newton", "isaaclab_assets", "isaaclab_rl", "isaaclab_tasks"]:
    sh(f"{PY} -m pip install --no-cache-dir -e {LAB}/source/{pkg} 2>&1 | tail -1",
       1200, f"install {pkg}", tail=1)
sh(f"{PY} -m pip install --no-cache-dir rsl-rl-lib 2>&1 | tail -1", 600, "rsl_rl", tail=1)

# --- inject the ice variant into the G1 task package -------------------------
G1DIR = pathlib.Path(f"{LAB}/source/isaaclab_tasks/isaaclab_tasks/manager_based/"
                     f"locomotion/velocity/config/g1")

(G1DIR / "ice_env_cfg.py").write_text(textwrap.dedent(f'''
    """G1 on ice. Generated by train_ice_isaac.py."""
    from isaaclab.utils.configclass import configclass
    from .flat_env_cfg import G1FlatEnvCfg


    @configclass
    class G1IceEnvCfg(G1FlatEnvCfg):
        def __post_init__(self):
            super().__post_init__()

            # THE experiment: stock is (0.8, 0.8) / (0.6, 0.6) -- a point, not a range.
            self.events.physics_material.params["static_friction_range"] = {ICE_STATIC}
            self.events.physics_material.params["dynamic_friction_range"] = {ICE_DYNAMIC}

            # Sliding is unavoidable on ice; a stiff penalty punishes the surface,
            # not the gait, and drives the policy toward standing still.
            self.rewards.feet_slide.weight = -0.01


    @configclass
    class G1IceEnvCfg_PLAY(G1IceEnvCfg):
        def __post_init__(self):
            super().__post_init__()
            self.scene.num_envs = 32
            self.observations.policy.enable_corruption = False
            self.events.base_external_force_torque = None
            self.events.push_robot = None
'''))

# Append registration to the package __init__ so parse_env_cfg / train.py find it.
with open(G1DIR / "__init__.py", "a") as f:
    f.write(textwrap.dedent('''

        # --- Himalaya ice variant -------------------------------------------
        import gymnasium as gym  # noqa: E402
        from . import agents  # noqa: E402

        gym.register(
            id="Isaac-Velocity-Flat-G1-Ice-v0",
            entry_point="isaaclab.envs:ManagerBasedRLEnv",
            disable_env_checker=True,
            kwargs={
                "env_cfg_entry_point": f"{__name__}.ice_env_cfg:G1IceEnvCfg",
                "rsl_rl_cfg_entry_point": f"{agents.__name__}.rsl_rl_ppo_cfg:G1FlatPPORunnerCfg",
            },
        )
        gym.register(
            id="Isaac-Velocity-Flat-G1-Ice-Play-v0",
            entry_point="isaaclab.envs:ManagerBasedRLEnv",
            disable_env_checker=True,
            kwargs={
                "env_cfg_entry_point": f"{__name__}.ice_env_cfg:G1IceEnvCfg_PLAY",
                "rsl_rl_cfg_entry_point": f"{agents.__name__}.rsl_rl_ppo_cfg:G1FlatPPORunnerCfg",
            },
        )
    '''))

print("\n--- registered ice env; verifying the override took effect ---", flush=True)
VERIFY = textwrap.dedent(f'''
    import os
    os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
    os.environ.setdefault("HOME", "/root")
    from isaaclab.app import AppLauncher
    app = AppLauncher(headless=True, device="cuda:0").app
    import gymnasium as gym
    import isaaclab_tasks  # noqa
    from isaaclab_tasks.utils import parse_env_cfg
    cfg = parse_env_cfg("{TASK}", device="cuda:0", num_envs=4)
    p = cfg.events.physics_material.params
    print("ICE static :", p["static_friction_range"], flush=True)
    print("ICE dynamic:", p["dynamic_friction_range"], flush=True)
    print("feet_slide weight:", cfg.rewards.feet_slide.weight, flush=True)
    assert p["static_friction_range"] == {ICE_STATIC}, "override did not apply!"
    print("OVERRIDE_OK", flush=True)
    app.close()
''')
pathlib.Path("verify.py").write_text(VERIFY)
if not sh(f"{PY} verify.py 2>&1 | grep -E 'ICE |feet_slide|OVERRIDE_OK|Error|assert' | tail -10",
          900, "verify override", tail=10):
    print("VERIFY FAILED - not spending GPU time on an unconfirmed env", flush=True)
    sys.exit(1)

train_py = subprocess.run(f"find {LAB} -path '*rsl_rl*' -name train.py | head -1",
                          shell=True, capture_output=True, text=True).stdout.strip()
OUT.mkdir(parents=True, exist_ok=True)
sync = subprocess.Popen(
    f"while true; do sleep 180; cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; done", shell=True)

print("\n" + "=" * 60 + f"\nTRAINING ON ICE  {ICE_STATIC}\n" + "=" * 60, flush=True)
ok = sh(f"cd {LAB} && {PY} {train_py} --task {TASK} --headless "
        f"--num_envs {NUM_ENVS} --max_iterations {MAX_ITER} 2>&1 "
        "| grep -vE 'neuraylib|material_library|\\[Warning\\]' | tail -60",
        5400, "train", tail=60)

sync.terminate()
sh(f"cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; find {OUT} -name '*.pt' | tail -5",
   600, "final sync", tail=8)
print("\nICE TRAINING", "COMPLETE" if ok else "FAILED", flush=True)
