# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["isaacsim[all,extscache]==6.0.1.0", "pip"]
# [tool.uv]
# extra-index-url = ["https://pypi.nvidia.com"]
# index-strategy = "unsafe-best-match"
# prerelease = "allow"
# ///
"""Objective D: fixed-line ascent -- climbing an icy slope on a rope.

The MuJoCo track built `fixed_line.py` and reasoned the design out properly:
real climbers do NOT grip the rope, they clip a mechanical ascender that slides up
freely and locks under load, so modelling grip as a MECHANISM is the faithful
choice rather than a shortcut. A rigid constraint was rejected there after it
carried 327 N of a 330 N robot -- a zip line, not an ascent.

Nothing trains in MuJoCo, so this ports the same idea to Isaac using the mechanism
that is already proven here: an external force on the torso. A tether is an upward
assist force, roughly a third of body weight, which is what taking your own weight
on an ascender feels like -- it helps, it does not carry you.

Built on the ice+slope config that reached 93.5%, so this is one change from a
known-good recipe -- the discipline that has separated every run that worked here
from every run that did not.

The tether is NOT in the policy observation. The robot must feel the assist
through its own dynamics, exactly as it must feel the surface -- same argument as
wind, and what makes the behaviour transferable.

Run:
  hf jobs uv run --detach --namespace iteratehack --flavor l40sx1 --timeout 3h \
      --env OMNI_KIT_ACCEPT_EULA=YES \
      -v hf://buckets/iteratehack/jobs-artifacts:/mnt \
      --label name=himalaya-traction --label task=train-tether \
      train_tether.py
"""

import os
import pathlib
import subprocess
import sys
import textwrap
import time

os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
os.environ.setdefault("HOME", "/root")

PY = sys.executable
LAB = "/tmp/IsaacLab"
OUT = pathlib.Path("/mnt/himalaya-g1/tether")
TASK = "Isaac-Velocity-Rough-G1-Tether-v0"
NUM_ENVS = 4096
MAX_ITER = int(os.environ.get("MAX_ITER", "3000"))


def sh(cmd, timeout, label, tail=15):
    print(f"\n$ {cmd}", flush=True)
    t0 = time.time()
    p = subprocess.run(cmd, shell=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print("\n".join(p.stdout.splitlines()[-tail:]), flush=True)
    print(f"[{label}] rc={p.returncode} in {time.time()-t0:.0f}s", flush=True)
    return p.returncode == 0


sh("apt-get update -qq && apt-get install -y -qq --no-install-recommends "
   "libgl1 libglu1-mesa libegl1 libvulkan1 libxrandr2 libxinerama1 libxcursor1 "
   "libxi6 libsm6 libice6 libxt6 libgomp1 git ffmpeg && echo apt-ok", 900, "apt", tail=2)
sh(f"git clone --depth 1 -q https://github.com/isaac-sim/IsaacLab.git {LAB} && echo cloned",
   900, "clone", tail=2)
for pkg in ["isaaclab", "isaaclab_ov", "isaaclab_physx", "isaaclab_ovphysx",
            "isaaclab_newton", "isaaclab_assets", "isaaclab_rl", "isaaclab_tasks",
            "isaaclab_visualizers"]:
    sh(f"{PY} -m pip install --no-cache-dir -e {LAB}/source/{pkg} 2>&1 | tail -1",
       1200, f"install {pkg}", tail=1)
sh(f"{PY} -m pip install --no-cache-dir rsl-rl-lib 2>&1 | tail -1", 600, "rsl_rl", tail=1)

G1DIR = pathlib.Path(f"{LAB}/source/isaaclab_tasks/isaaclab_tasks/manager_based/"
                     f"locomotion/velocity/config/g1")
(G1DIR / "tether_env_cfg.py").write_text(textwrap.dedent('''
    """G1 ascending an icy slope on a fixed line. Generated by train_tether.py."""
    import isaaclab.envs.mdp as mdp
    from isaaclab.managers import EventTermCfg as EventTerm
    from isaaclab.managers import SceneEntityCfg
    from isaaclab.utils.configclass import configclass

    from .rough_env_cfg import G1RoughEnvCfg


    @configclass
    class G1TetherEnvCfg(G1RoughEnvCfg):
        def __post_init__(self):
            super().__post_init__()

            # ice -> rock, as in the 93.5% ice+slope run
            self.events.physics_material.params["static_friction_range"] = (0.05, 1.0)
            self.events.physics_material.params["dynamic_friction_range"] = (0.04, 0.9)
            self.rewards.feet_slide.weight = -0.01

            # The ascender: a sustained upward assist at the torso, re-applied
            # every 0.4-1.0 s so it is a continuous load rather than a shove.
            #
            # The G1 is ~35 kg (~340 N). 80-140 N up is roughly a third of body
            # weight -- what taking your weight on a jumar feels like. It helps you
            # up the slope; it does not carry you, which is the failure mode that
            # made the MuJoCo rigid-constraint version a zip line.
            self.events.tether = EventTerm(
                func=mdp.apply_external_force_torque,
                mode="interval",
                interval_range_s=(0.4, 1.0),
                params={
                    "asset_cfg": SceneEntityCfg("robot", body_names=["torso_link"]),
                    "force_range": (80.0, 140.0),
                    "torque_range": (-5.0, 5.0),
                },
            )
            # Climbing means going UP the slope steadily, not strolling.
            self.commands.base_velocity.ranges.lin_vel_x = (0.4, 0.9)


    @configclass
    class G1TetherEnvCfg_PLAY(G1TetherEnvCfg):
        def __post_init__(self):
            super().__post_init__()
            self.scene.num_envs = 1
            self.observations.policy.enable_corruption = False
'''))

with open(G1DIR / "__init__.py", "a") as f:
    f.write(textwrap.dedent('''

        import gymnasium as gym  # noqa: E402
        from . import agents  # noqa: E402
        for _id, _cls in [("Isaac-Velocity-Rough-G1-Tether-v0", "G1TetherEnvCfg"),
                          ("Isaac-Velocity-Rough-G1-Tether-Play-v0", "G1TetherEnvCfg_PLAY")]:
            gym.register(
                id=_id,
                entry_point="isaaclab.envs:ManagerBasedRLEnv",
                disable_env_checker=True,
                kwargs={"env_cfg_entry_point": f"{__name__}.tether_env_cfg:{_cls}",
                        "rsl_rl_cfg_entry_point":
                            f"{agents.__name__}.rsl_rl_ppo_cfg:G1RoughPPORunnerCfg"},
            )
    '''))

VERIFY = textwrap.dedent(f'''
    import os
    os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
    os.environ.setdefault("HOME", "/root")
    from isaaclab.app import AppLauncher
    app = AppLauncher(headless=True, device="cuda:0").app
    import isaaclab_tasks  # noqa
    from isaaclab_tasks.utils import parse_env_cfg
    cfg = parse_env_cfg("{TASK}", device="cuda:0", num_envs=4)
    print("tether mode :", cfg.events.tether.mode, flush=True)
    print("tether force:", cfg.events.tether.params["force_range"], flush=True)
    print("friction  :", cfg.events.physics_material.params["static_friction_range"],
          flush=True)
    print("terrain   :", cfg.scene.terrain.terrain_type, flush=True)
    assert cfg.events.tether.mode == "interval", "tether is not sustained!"
    assert cfg.scene.terrain.terrain_type == "generator", "not on slopes!"
    print("VERIFY_OK", flush=True)
    app.close()
''')
pathlib.Path("verify.py").write_text(VERIFY)
if not sh(f"{PY} verify.py 2>&1 | grep -E 'tether|friction|terrain|VERIFY_OK|Error|assert' "
          "| tail -8", 900, "verify", tail=8):
    sys.exit("verification failed - not spending GPU time")

train_py = subprocess.run(f"find {LAB} -path '*rsl_rl*' -name train.py | head -1",
                          shell=True, capture_output=True, text=True).stdout.strip()
OUT.mkdir(parents=True, exist_ok=True)
sync = subprocess.Popen(
    f"while true; do sleep 180; cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; done", shell=True)
ok = sh(f"cd {LAB} && {PY} {train_py} --task {TASK} --headless "
        f"--num_envs {NUM_ENVS} --max_iterations {MAX_ITER} 2>&1 "
        "| grep -vE 'neuraylib|material_library|\\[Warning\\]' | tail -50",
        10800, "train", tail=50)
sync.terminate()
sh(f"cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; find {OUT} -name '*.pt' | tail -3",
   600, "final sync", tail=5)
print("\nTETHER TRAINING", "COMPLETE" if ok else "FAILED", flush=True)
