# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["isaacsim[all,extscache]==6.0.1.0", "pip"]
# [tool.uv]
# extra-index-url = ["https://pypi.nvidia.com"]
# index-strategy = "unsafe-best-match"
# prerelease = "allow"
# ///
"""Fall recovery: the G1 starts on the ground and has to stand back up -- on ice.

Track 1's second bullet, and a genuinely different problem from locomotion rather
than a variation on it:

  * Falling is the START state, not the failure. `terminations.base_contact` must
    be removed or every episode ends on the first frame.
  * There is nothing to track. Velocity-tracking rewards are meaningless lying on
    your back, so they go to zero and are replaced by "get the torso up and level".
  * Ice makes it harder in a specific way: pushing up needs the hands and feet to
    PURCHASE against the ground, and mu=0.06 is what a stuck limb slides on.

Reward shape, deliberately small: height and uprightness carry the task, the stock
regularisers (torque, action rate, joint limits) keep the motion physical. A
hand-tuned recovery reward would be a second research project; this is the smallest
thing that expresses "end up standing".

Starting poses are randomised across roll and pitch, so the policy has to recover
from face-down, back-down and side-down rather than memorising one scripted
get-up.

Run:
  hf jobs uv run --detach --namespace iteratehack --flavor a100-large --timeout 3h \
      --env OMNI_KIT_ACCEPT_EULA=YES \
      -v hf://buckets/iteratehack/jobs-artifacts:/mnt \
      --label name=himalaya-traction --label task=train-getup \
      train_getup.py
"""

import os
import pathlib
import subprocess
import sys
import textwrap
import time

os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
os.environ.setdefault("HOME", "/root")
# See above: forces protobuf away from the C++ descriptor pool that
# abort()s on duplicate registration.
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

PY = sys.executable
LAB = "/tmp/IsaacLab"
TASK = "Isaac-Getup-G1-Ice-v0"
NUM_ENVS = int(os.environ.get("GETUP_ENVS", "1024"))
MAX_ITER = int(os.environ.get("MAX_ITER", "3000"))
# Start-pose difficulty, overridable so a loop can run a curriculum: begin with a
# stumble (nearly upright) and work down to fully prone.
Z_MIN = os.environ.get("GETUP_Z_MIN", "-0.32")
Z_MAX = os.environ.get("GETUP_Z_MAX", "-0.05")
ROLL = os.environ.get("GETUP_ROLL", "0.25")
EPISODE_S = os.environ.get("GETUP_EPISODE_S", "10.0")
RUN_TAG = os.environ.get("GETUP_TAG", "v3")
# Defined AFTER RUN_TAG: it was above it, and every rung of the
# recovery ladder died on NameError in five minutes because of it.
OUT = pathlib.Path(f"/mnt/himalaya-g1/getup-{RUN_TAG}")


def sh(cmd, timeout, label, tail=15):
    print(f"\n$ {cmd}", flush=True)
    t0 = time.time()
    # executable=/bin/bash: shell=True defaults to /bin/sh (dash), which does not
    # support `set -o pipefail`, and the training command exited rc=2 before doing
    # anything at all.
    p = subprocess.run(cmd, shell=True, timeout=timeout, executable="/bin/bash",
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print("\n".join(p.stdout.splitlines()[-tail:]), flush=True)
    print(f"[{label}] rc={p.returncode} in {time.time()-t0:.0f}s", flush=True)
    return p.returncode == 0


sh("apt-get update -qq && apt-get install -y -qq --no-install-recommends "
   "libgl1 libglu1-mesa libegl1 libvulkan1 libxrandr2 libxinerama1 libxcursor1 "
   "libxi6 libsm6 libice6 libxt6 libgomp1 git ffmpeg && echo apt-ok", 900, "apt", tail=2)
sh(f"git clone --depth 1 -q https://github.com/isaac-sim/IsaacLab.git {LAB} && echo cloned",
   900, "clone", tail=2)
for pkg in ["isaaclab", "isaaclab_ov", "isaaclab_physx", "isaaclab_ovphysx",
            "isaaclab_newton", "isaaclab_assets", "isaaclab_rl", "isaaclab_tasks",
            "isaaclab_visualizers", "isaaclab_contrib"]:
    sh(f"{PY} -m pip install --no-cache-dir -e {LAB}/source/{pkg} 2>&1 | tail -1",
       1200, f"install {pkg}", tail=1)
sh(f"{PY} -m pip install --no-cache-dir 'rsl-rl-lib==5.0.1' onnxscript 2>&1 | tail -1",
   600, "rsl_rl", tail=1)

G1DIR = pathlib.Path(f"{LAB}/source/isaaclab_tasks/isaaclab_tasks/manager_based/"
                     f"locomotion/velocity/config/g1")

(G1DIR / "getup_env_cfg.py").write_text(textwrap.dedent('''
    """G1 fall recovery on ice. Generated by train_getup.py."""
    import os

    import isaaclab.envs.mdp as mdp
    from isaaclab.managers import RewardTermCfg as RewTerm
    from isaaclab.managers import SceneEntityCfg
    from isaaclab.utils.configclass import configclass

    from .flat_env_cfg import G1FlatEnvCfg

    import torch
    from isaaclab.assets import Articulation
    from isaaclab.envs import ManagerBasedRLEnv

    # G1 pelvis height standing.
    STAND_HEIGHT = 0.74

    # Read straight from the environment: this module is generated as a plain
    # string, so interpolating would mean escaping every dict literal in it.
    Z_MIN = float(os.environ.get("GETUP_Z_MIN", "-0.45"))
    Z_MAX = float(os.environ.get("GETUP_Z_MAX", "-0.05"))
    ROLL = float(os.environ.get("GETUP_ROLL", "1.8"))
    EPISODE_S = float(os.environ.get("GETUP_EPISODE_S", "10.0"))


    def standing_bonus(env: ManagerBasedRLEnv,
                       asset_cfg: SceneEntityCfg = SceneEntityCfg("robot")):
        """Strictly POSITIVE, ~0 when prone, maximal standing upright and tall.

        The whole point is to give recovery something to climb toward. Height and
        uprightness are multiplied, not added, so the robot cannot collect reward
        by rearing up while still face-down, nor by lying flat but level.

        projected_gravity_b[:, 2] is -1 when the torso is upright and ~0 on its
        side, so (-g_z) maps cleanly to [0, 1] as an uprightness score.
        """
        asset: Articulation = env.scene[asset_cfg.name]
        h = asset.data.root_pos_w[:, 2]
        height_score = torch.exp(-torch.abs(h - STAND_HEIGHT) / 0.25)
        upright = torch.clamp(-asset.data.projected_gravity_b[:, 2], 0.0, 1.0)
        return height_score * upright


    @configclass
    class G1GetupIceEnvCfg(G1FlatEnvCfg):
        def __post_init__(self):
            super().__post_init__()

            # ---- start on the ground -----------------------------------------
            # z is an OFFSET from the default root height, so -0.45 puts the pelvis
            # near the floor. Full yaw, and roll/pitch wide enough to produce
            # face-down, back-down and side-down starts rather than one pose.
            # v1 started FULLY sprawled -- z -0.50..-0.40 with roll across the
            # whole circle -- and after 3000 iterations success_rate was 0.000 with
            # base_height -1.83, i.e. it never got off the ground. Prone-to-standing
            # is long-horizon and that start gives almost no gradient toward
            # standing.
            #
            # v2 spans the range instead: some episodes start nearly upright (a
            # stumble), some half-down, some fully prone. The easy ones bootstrap a
            # recovery behaviour that the hard ones can then extend -- a curriculum
            # by sampling rather than by scheduling, which needs no extra machinery.
            self.events.reset_base.params["pose_range"] = {
                "x": (-0.3, 0.3), "y": (-0.3, 0.3), "z": (Z_MIN, Z_MAX),
                "roll": (-ROLL, ROLL), "pitch": (-1.0, 1.0), "yaw": (-3.14, 3.14),
            }
            self.events.reset_base.params["velocity_range"] = {
                "x": (0.0, 0.0), "y": (0.0, 0.0), "z": (0.0, 0.0),
                "roll": (0.0, 0.0), "pitch": (0.0, 0.0), "yaw": (0.0, 0.0),
            }
            # Sprawled limbs, not a tidy default pose.
            self.events.reset_robot_joints.params["position_range"] = (0.6, 1.4)

            # ---- being on the ground is the PREMISE, not a failure -----------
            # base_contact is left EXACTLY as shipped. Both ways of disabling it
            # break Isaac: setting it to None segfaults at a fixed 312 s (identical
            # at 64/30 and 4096/3000, so not a scale problem), and raising its
            # threshold aborts at 22 s. The env is only viable if the torso never
            # touches the ground -- which a CROUCH start guarantees while still
            # being the second half of a real get-up.

            # Long enough to actually complete a recovery.
            self.episode_length_s = EPISODE_S

            # ---- nothing to track while lying down ---------------------------
            self.commands.base_velocity.ranges.lin_vel_x = (0.0, 0.0)
            self.commands.base_velocity.ranges.lin_vel_y = (0.0, 0.0)
            self.commands.base_velocity.ranges.ang_vel_z = (0.0, 0.0)
            self.rewards.track_lin_vel_xy_exp.weight = 0.0
            self.rewards.track_ang_vel_z_exp.weight = 0.0
            self.rewards.feet_air_time.weight = 0.0
            self.rewards.feet_slide.weight = 0.0
            self.rewards.termination_penalty.weight = 0.0

            # ---- stand up and stay level -------------------------------------
            # THE BUG IN v1 AND v2: every remaining reward was NEGATIVE. The
            # positive terms (velocity tracking, feet air time) were zeroed because
            # they are meaningless lying down, which left only penalties -- so with
            # no termination the optimal policy was TO NOT MOVE. Lying still
            # minimises torque and action-rate cost. Both runs converged to exactly
            # that: base_height -1.81 and -1.83, success 0.000, twice.
            #
            # Recovery needs something to CLIMB TOWARD. `standing_bonus` is
            # strictly positive, near zero when prone and maximal when upright and
            # tall, so the gradient points off the ground from the first frame.
            self.rewards.standing = RewTerm(func=standing_bonus, weight=8.0)

            self.rewards.flat_orientation_l2.weight = -2.0
            self.rewards.base_height = RewTerm(
                func=mdp.base_height_l2,
                weight=-2.0,
                params={"target_height": STAND_HEIGHT,
                        "asset_cfg": SceneEntityCfg("robot")},
            )
            # Standing up is a large, fast, high-torque motion. The locomotion
            # defaults penalise exactly that because they are tuned for efficient
            # walking, so they were fighting the task. Relaxed by ~10x.
            self.rewards.action_rate_l2.weight = -0.001
            self.rewards.dof_torques_l2.weight = -1.0e-6
            self.rewards.dof_acc_l2.weight = -1.0e-8
            # Deviation penalties assume a nominal standing pose; getting up
            # requires leaving it entirely.
            self.rewards.joint_deviation_hip.weight = 0.0
            self.rewards.joint_deviation_arms.weight = 0.0
            self.rewards.joint_deviation_torso.weight = 0.0

            # ---- contact budget ----------------------------------------------
            # Removing base_contact termination means robots lie in deep
            # penetrating contact for the WHOLE episode instead of resetting on
            # touchdown -- unique to this task -- and at 4096 envs that overflowed
            # PhysX's rigid-patch buffer, SEGFAULTING (rc=139) rather than raising.
            #
            # Replacing self.sim to raise the buffer made it worse (SIGABRT in 22 s):
            # G1FlatEnvCfg builds sim from a PresetCfg carrying BOTH a PhysX and a
            # Newton MJWarp preset, and substituting a plain SimulationCfg discards
            # that structure. Fewer environments achieves the same thing without
            # touching a config shape I do not fully control.

            # ---- on ice ------------------------------------------------------
            # Hands and feet need purchase to push against; 0.06 is what a limb
            # slides on. Spanning up to rock keeps it usable on mixed ground.
            self.events.physics_material.params["static_friction_range"] = (0.05, 1.0)
            self.events.physics_material.params["dynamic_friction_range"] = (0.04, 0.9)


    @configclass
    class G1GetupIceEnvCfg_PLAY(G1GetupIceEnvCfg):
        def __post_init__(self):
            super().__post_init__()
            self.scene.num_envs = 16
            self.observations.policy.enable_corruption = False
            self.events.push_robot = None
            self.events.base_external_force_torque = None
'''))

with open(G1DIR / "__init__.py", "a") as f:
    f.write(textwrap.dedent('''

        import gymnasium as gym  # noqa: E402
        from . import agents  # noqa: E402

        for _id, _cls in [("Isaac-Getup-G1-Ice-v0", "G1GetupIceEnvCfg"),
                          ("Isaac-Getup-G1-Ice-Play-v0", "G1GetupIceEnvCfg_PLAY")]:
            gym.register(
                id=_id,
                entry_point="isaaclab.envs:ManagerBasedRLEnv",
                disable_env_checker=True,
                kwargs={
                    "env_cfg_entry_point": f"{__name__}.getup_env_cfg:{_cls}",
                    "rsl_rl_cfg_entry_point":
                        f"{agents.__name__}.rsl_rl_ppo_cfg:G1FlatPPORunnerCfg",
                },
            )
    '''))

# This env changes more than any previous one -- termination removed, rewards
# rewritten, reset re-posed. Verify every piece before spending an hour of GPU.
VERIFY = textwrap.dedent(f'''
    import os, torch
    os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
    os.environ.setdefault("HOME", "/root")
    from isaaclab.app import AppLauncher
    app = AppLauncher(headless=True, device="cuda:0").app
    import gymnasium as gym
    import isaaclab_tasks  # noqa
    from isaaclab_tasks.utils import parse_env_cfg
    cfg = parse_env_cfg("{TASK}", device="cuda:0", num_envs=64)
    print("base_contact termination:", cfg.terminations.base_contact, flush=True)
    print("episode_length_s        :", cfg.episode_length_s, flush=True)
    print("reset z range           :", cfg.events.reset_base.params["pose_range"]["z"],
          flush=True)
    print("base_height reward      :", cfg.rewards.base_height.weight, flush=True)
    print("friction                :",
          cfg.events.physics_material.params["static_friction_range"], flush=True)

    # The real check: do the robots actually START on the ground?
    env = gym.make("{TASK}", cfg=cfg)
    env.reset()
    h = env.unwrapped.scene["robot"].data.root_pos_w[:, 2]
    print(f"start pelvis height: mean {{h.mean():.3f}} min {{h.min():.3f}} "
          f"max {{h.max():.3f}}", flush=True)
    expected = 0.74 + (float(os.environ.get("GETUP_Z_MIN", "-0.45")) + float(os.environ.get("GETUP_Z_MAX", "-0.05"))) / 2
    assert abs(h.mean() - expected) < 0.25, (
        f"start height {{h.mean():.3f}} does not match the configured "
        f"range (expected ~{{expected:.3f}})")
    open("/tmp/verify_ok", "w").write("ok")
    print("VERIFY_OK", flush=True)
    env.close(); app.close()
''')
pathlib.Path("/tmp/verify_ok").unlink(missing_ok=True)
pathlib.Path("verify.py").write_text(VERIFY)
_v = subprocess.run(f"{PY} verify.py", shell=True, timeout=900, executable="/bin/bash",
                    stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
for _ln in _v.stdout.splitlines():
    if any(k in _ln for k in ("termination", "episode_length", "reset z", "base_height",
                              "friction", "start pelvis", "VERIFY_OK", "Error", "assert")):
        print(_ln, flush=True)
# Exit code is unusable here -- Isaac Sim returns 0 even after an uncaught
# AssertionError. The sentinel file is the only trustworthy signal.
_ok = pathlib.Path("/tmp/verify_ok").exists()
print(f"[verify] rc={_v.returncode} sentinel={_ok}", flush=True)
if not _ok:
    print(_v.stdout[-2000:], flush=True)
    sys.exit("verification failed (no sentinel) - not spending GPU time")

train_py = subprocess.run(f"find {LAB} -path '*rsl_rl*' -name train.py | head -1",
                          shell=True, capture_output=True, text=True).stdout.strip()
OUT.mkdir(parents=True, exist_ok=True)
sync = subprocess.Popen(
    f"while true; do sleep 180; cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; done", shell=True)

print("\n" + "=" * 60 + f"\nTRAINING FALL RECOVERY ON ICE  {MAX_ITER} iters\n" + "=" * 60,
      flush=True)

TRAINER = textwrap.dedent('''
    """Custom trainer: AppLauncher FIRST, then every Isaac import.

    IsaacLab's own scripts/reinforcement_learning/rsl_rl/train.py cannot be used
    here. Its @hydra_task_config decorator imports isaaclab_tasks -- and therefore
    interactive_scene -> isaaclab_contrib -> a second grpc/protobuf -- BEFORE
    SimulationApp is instantiated. Isaac warns about exactly this ("import
    statements must take place after the SimulationApp class has been
    instantiated") and the consequence is a duplicate registration of
    grpc/health/v1/health.proto and an abort() with "free(): invalid pointer".

    Every script here that works (the verify step, the filming loop) instantiates
    AppLauncher first. This does the same, which is the whole fix.
    """
    import os, sys
    os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
    os.environ.setdefault("HOME", "/root")

    from isaaclab.app import AppLauncher
    app = AppLauncher(headless=True, device="cuda:0").app     # BEFORE any Isaac import

    import gymnasium as gym
    import isaaclab_tasks  # noqa: F401
    from isaaclab_tasks.utils import load_cfg_from_registry, parse_env_cfg
    from isaaclab_rl.rsl_rl import RslRlVecEnvWrapper
    from rsl_rl.runners import OnPolicyRunner

    TASK = sys.argv[1]
    NUM_ENVS = int(sys.argv[2])
    MAX_ITER = int(sys.argv[3])
    LOG_DIR = sys.argv[4]

    env_cfg = parse_env_cfg(TASK, device="cuda:0", num_envs=NUM_ENVS)
    agent_cfg = load_cfg_from_registry(TASK, "rsl_rl_cfg_entry_point")
    # load_cfg_from_registry hands back the CLASS for some entry points and an
    # instance for others; an uninstantiated one produced the confusing
    # "MLPModel.__init__() got an unexpected keyword argument 'stochastic'".
    if isinstance(agent_cfg, type):
        agent_cfg = agent_cfg()
    agent_cfg.max_iterations = MAX_ITER

    env = gym.make(TASK, cfg=env_cfg)
    env = RslRlVecEnvWrapper(env)
    runner = OnPolicyRunner(env, agent_cfg.to_dict(), log_dir=LOG_DIR, device="cuda:0")
    print(f"TRAINER_START {TASK} envs={NUM_ENVS} iters={MAX_ITER}", flush=True)
    runner.learn(num_learning_iterations=MAX_ITER, init_at_random_ep_len=True)
    print("TRAINER_DONE", flush=True)
    env.close()
    app.close()
''')
pathlib.Path("/tmp/trainer.py").write_text(TRAINER)

_t = subprocess.run(
    [PY, "/tmp/trainer.py", TASK, str(NUM_ENVS), str(MAX_ITER), f"{LAB}/logs/rsl_rl/getup"],
    cwd=LAB, timeout=10800, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
_lines = [l for l in _t.stdout.splitlines()
          if not any(k in l for k in ("neuraylib", "material_library", "[Warning]"))]
print("\n".join(_lines[-80:]), flush=True)
print(f"[train] rc={_t.returncode}", flush=True)
if _t.returncode != 0:
    print("=== FIRST 60 LINES (the error is usually here, not the tail) ===", flush=True)
    print("\n".join(_lines[:60]), flush=True)
ok = ("TRAINER_DONE" in _t.stdout) and _t.returncode == 0
# The exit code alone is not evidence: the previous run printed a full
# Traceback and still exited 0. TRAINER_DONE only prints after learn().
# A crash inside Kit still exits non-zero; without pipefail the pipeline reported
# tail's status and this said COMPLETE with nothing trained.
if not ok:
    print("TRAINING DID NOT SUCCEED -- see the trace above", flush=True)

sync.terminate()
sh(f"cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; find {OUT} -name '*.pt' | tail -5",
   600, "final sync", tail=8)
print("\nGETUP TRAINING", "COMPLETE" if ok else "FAILED", flush=True)
