# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["isaacsim[all,extscache]==6.0.1.0", "pip"]
# [tool.uv]
# extra-index-url = ["https://pypi.nvidia.com"]
# index-strategy = "unsafe-best-match"
# prerelease = "allow"
# ///
"""Objective C: wind resistance -- on ice, on slopes.

Wind exists in the MuJoCo track (`wind.py`, drag + centre-of-pressure torque +
AR(1) gusts) but nothing trains there, so the capability has never been
demonstrated. Isaac Lab already has the mechanism: an event term that applies an
external force/torque to a body. Sustained wind is that term in `interval` mode
with a short interval, rather than the usual once-per-reset shove.

Built on the ice+slope config that reached 93.5%, so this is one change from a
known-good recipe -- the discipline that has separated every run that worked here
from every run that did not.

Force scale: the G1 is ~35 kg. 40-90 N lateral against a walking humanoid is a
stiff, shoving wind -- enough to require a postural response, not so much that it
is simply thrown. Applied at the torso, which is where a real gust loads a body.

Wind is NOT in the policy observation, deliberately. A real robot has no
anemometer; it must infer loading from its IMU and joint tracking error. That is
the same argument `CLAUDE.md` makes for the MuJoCo version, and it is what makes
the learned behaviour transferable rather than a cheat.

Run:
  hf jobs uv run --detach --namespace iteratehack --flavor l40sx1 --timeout 3h \
      --env OMNI_KIT_ACCEPT_EULA=YES \
      -v hf://buckets/iteratehack/jobs-artifacts:/mnt \
      --label name=himalaya-traction --label task=train-wind \
      train_wind.py
"""

import os
import pathlib
import subprocess
import sys
import textwrap
import time

os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
os.environ.setdefault("HOME", "/root")

PY = sys.executable
LAB = "/tmp/IsaacLab"
OUT = pathlib.Path("/mnt/himalaya-g1/wind")
TASK = "Isaac-Velocity-Rough-G1-Wind-v0"
NUM_ENVS = 4096
MAX_ITER = int(os.environ.get("MAX_ITER", "3000"))


def sh(cmd, timeout, label, tail=15):
    print(f"\n$ {cmd}", flush=True)
    t0 = time.time()
    p = subprocess.run(cmd, shell=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print("\n".join(p.stdout.splitlines()[-tail:]), flush=True)
    print(f"[{label}] rc={p.returncode} in {time.time()-t0:.0f}s", flush=True)
    return p.returncode == 0


sh("apt-get update -qq && apt-get install -y -qq --no-install-recommends "
   "libgl1 libglu1-mesa libegl1 libvulkan1 libxrandr2 libxinerama1 libxcursor1 "
   "libxi6 libsm6 libice6 libxt6 libgomp1 git ffmpeg && echo apt-ok", 900, "apt", tail=2)
sh(f"git clone --depth 1 -q https://github.com/isaac-sim/IsaacLab.git {LAB} && echo cloned",
   900, "clone", tail=2)
for pkg in ["isaaclab", "isaaclab_ov", "isaaclab_physx", "isaaclab_ovphysx",
            "isaaclab_newton", "isaaclab_assets", "isaaclab_rl", "isaaclab_tasks",
            "isaaclab_visualizers"]:
    sh(f"{PY} -m pip install --no-cache-dir -e {LAB}/source/{pkg} 2>&1 | tail -1",
       1200, f"install {pkg}", tail=1)
sh(f"{PY} -m pip install --no-cache-dir rsl-rl-lib 2>&1 | tail -1", 600, "rsl_rl", tail=1)

G1DIR = pathlib.Path(f"{LAB}/source/isaaclab_tasks/isaaclab_tasks/manager_based/"
                     f"locomotion/velocity/config/g1")
(G1DIR / "wind_env_cfg.py").write_text(textwrap.dedent('''
    """G1 on icy slopes IN WIND. Generated by train_wind.py."""
    import isaaclab.envs.mdp as mdp
    from isaaclab.managers import EventTermCfg as EventTerm
    from isaaclab.managers import SceneEntityCfg
    from isaaclab.utils.configclass import configclass

    from .rough_env_cfg import G1RoughEnvCfg


    @configclass
    class G1WindEnvCfg(G1RoughEnvCfg):
        def __post_init__(self):
            super().__post_init__()

            # ice -> rock, as in the 93.5% ice+slope run
            self.events.physics_material.params["static_friction_range"] = (0.05, 1.0)
            self.events.physics_material.params["dynamic_friction_range"] = (0.04, 0.9)
            self.rewards.feet_slide.weight = -0.01

            # SUSTAINED wind, not a one-off shove. interval mode re-applies every
            # 0.5-1.5 s, so the robot lives under continuous lateral loading with
            # gust-like variation, rather than being hit once at reset.
            #
            # The G1 is ~35 kg. 40-90 N lateral is a stiff shoving wind: it forces
            # a postural response without simply throwing the robot.
            self.events.wind = EventTerm(
                func=mdp.apply_external_force_torque,
                mode="interval",
                interval_range_s=(0.5, 1.5),
                params={
                    "asset_cfg": SceneEntityCfg("robot", body_names=["torso_link"]),
                    "force_range": (-90.0, 90.0),
                    "torque_range": (-12.0, 12.0),
                },
            )


    @configclass
    class G1WindEnvCfg_PLAY(G1WindEnvCfg):
        def __post_init__(self):
            super().__post_init__()
            self.scene.num_envs = 1
            self.observations.policy.enable_corruption = False
'''))

with open(G1DIR / "__init__.py", "a") as f:
    f.write(textwrap.dedent('''

        import gymnasium as gym  # noqa: E402
        from . import agents  # noqa: E402
        for _id, _cls in [("Isaac-Velocity-Rough-G1-Wind-v0", "G1WindEnvCfg"),
                          ("Isaac-Velocity-Rough-G1-Wind-Play-v0", "G1WindEnvCfg_PLAY")]:
            gym.register(
                id=_id,
                entry_point="isaaclab.envs:ManagerBasedRLEnv",
                disable_env_checker=True,
                kwargs={"env_cfg_entry_point": f"{__name__}.wind_env_cfg:{_cls}",
                        "rsl_rl_cfg_entry_point":
                            f"{agents.__name__}.rsl_rl_ppo_cfg:G1RoughPPORunnerCfg"},
            )
    '''))

VERIFY = textwrap.dedent(f'''
    import os
    os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
    os.environ.setdefault("HOME", "/root")
    from isaaclab.app import AppLauncher
    app = AppLauncher(headless=True, device="cuda:0").app
    import isaaclab_tasks  # noqa
    from isaaclab_tasks.utils import parse_env_cfg
    cfg = parse_env_cfg("{TASK}", device="cuda:0", num_envs=4)
    print("wind mode :", cfg.events.wind.mode, flush=True)
    print("wind force:", cfg.events.wind.params["force_range"], flush=True)
    print("friction  :", cfg.events.physics_material.params["static_friction_range"],
          flush=True)
    print("terrain   :", cfg.scene.terrain.terrain_type, flush=True)
    assert cfg.events.wind.mode == "interval", "wind is not sustained!"
    assert cfg.scene.terrain.terrain_type == "generator", "not on slopes!"
    print("VERIFY_OK", flush=True)
    app.close()
''')
pathlib.Path("verify.py").write_text(VERIFY)
if not sh(f"{PY} verify.py 2>&1 | grep -E 'wind|friction|terrain|VERIFY_OK|Error|assert' "
          "| tail -8", 900, "verify", tail=8):
    sys.exit("verification failed - not spending GPU time")

train_py = subprocess.run(f"find {LAB} -path '*rsl_rl*' -name train.py | head -1",
                          shell=True, capture_output=True, text=True).stdout.strip()
OUT.mkdir(parents=True, exist_ok=True)
sync = subprocess.Popen(
    f"while true; do sleep 180; cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; done", shell=True)
ok = sh(f"cd {LAB} && {PY} {train_py} --task {TASK} --headless "
        f"--num_envs {NUM_ENVS} --max_iterations {MAX_ITER} 2>&1 "
        "| grep -vE 'neuraylib|material_library|\\[Warning\\]' | tail -50",
        10800, "train", tail=50)
sync.terminate()
sh(f"cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; find {OUT} -name '*.pt' | tail -3",
   600, "final sync", tail=5)
print("\nWIND TRAINING", "COMPLETE" if ok else "FAILED", flush=True)
