# /// script
# requires-python = ">=3.12,<3.13"
# dependencies = ["isaacsim[all,extscache]==6.0.1.0", "pip"]
# [tool.uv]
# extra-index-url = ["https://pypi.nvidia.com"]
# index-strategy = "unsafe-best-match"
# prerelease = "allow"
# ///
"""Fall recovery: the G1 starts on the ground and has to stand back up -- on ice.

Track 1's second bullet, and a genuinely different problem from locomotion rather
than a variation on it:

  * Falling is the START state, not the failure. `terminations.base_contact` must
    be removed or every episode ends on the first frame.
  * There is nothing to track. Velocity-tracking rewards are meaningless lying on
    your back, so they go to zero and are replaced by "get the torso up and level".
  * Ice makes it harder in a specific way: pushing up needs the hands and feet to
    PURCHASE against the ground, and mu=0.06 is what a stuck limb slides on.

Reward shape, deliberately small: height and uprightness carry the task, the stock
regularisers (torque, action rate, joint limits) keep the motion physical. A
hand-tuned recovery reward would be a second research project; this is the smallest
thing that expresses "end up standing".

Starting poses are randomised across roll and pitch, so the policy has to recover
from face-down, back-down and side-down rather than memorising one scripted
get-up.

Run:
  hf jobs uv run --detach --namespace iteratehack --flavor a100-large --timeout 3h \
      --env OMNI_KIT_ACCEPT_EULA=YES \
      -v hf://buckets/iteratehack/jobs-artifacts:/mnt \
      --label name=himalaya-traction --label task=train-getup \
      train_getup.py
"""

import os
import pathlib
import subprocess
import sys
import textwrap
import time

os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
os.environ.setdefault("HOME", "/root")

PY = sys.executable
LAB = "/tmp/IsaacLab"
OUT = pathlib.Path("/mnt/himalaya-g1/getup-v2")
TASK = "Isaac-Getup-G1-Ice-v0"
NUM_ENVS = 4096
MAX_ITER = int(os.environ.get("MAX_ITER", "3000"))


def sh(cmd, timeout, label, tail=15):
    print(f"\n$ {cmd}", flush=True)
    t0 = time.time()
    p = subprocess.run(cmd, shell=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print("\n".join(p.stdout.splitlines()[-tail:]), flush=True)
    print(f"[{label}] rc={p.returncode} in {time.time()-t0:.0f}s", flush=True)
    return p.returncode == 0


sh("apt-get update -qq && apt-get install -y -qq --no-install-recommends "
   "libgl1 libglu1-mesa libegl1 libvulkan1 libxrandr2 libxinerama1 libxcursor1 "
   "libxi6 libsm6 libice6 libxt6 libgomp1 git ffmpeg && echo apt-ok", 900, "apt", tail=2)
sh(f"git clone --depth 1 -q https://github.com/isaac-sim/IsaacLab.git {LAB} && echo cloned",
   900, "clone", tail=2)
for pkg in ["isaaclab", "isaaclab_ov", "isaaclab_physx", "isaaclab_ovphysx",
            "isaaclab_newton", "isaaclab_assets", "isaaclab_rl", "isaaclab_tasks",
            "isaaclab_visualizers"]:
    sh(f"{PY} -m pip install --no-cache-dir -e {LAB}/source/{pkg} 2>&1 | tail -1",
       1200, f"install {pkg}", tail=1)
sh(f"{PY} -m pip install --no-cache-dir rsl-rl-lib 2>&1 | tail -1", 600, "rsl_rl", tail=1)

G1DIR = pathlib.Path(f"{LAB}/source/isaaclab_tasks/isaaclab_tasks/manager_based/"
                     f"locomotion/velocity/config/g1")

(G1DIR / "getup_env_cfg.py").write_text(textwrap.dedent('''
    """G1 fall recovery on ice. Generated by train_getup.py."""
    import isaaclab.envs.mdp as mdp
    from isaaclab.managers import RewardTermCfg as RewTerm
    from isaaclab.managers import SceneEntityCfg
    from isaaclab.utils.configclass import configclass

    from .flat_env_cfg import G1FlatEnvCfg

    # G1 pelvis height standing. The velocity task uses 0.5 as its base-height
    # target elsewhere; standing tall is what we actually want to reward here.
    STAND_HEIGHT = 0.74


    @configclass
    class G1GetupIceEnvCfg(G1FlatEnvCfg):
        def __post_init__(self):
            super().__post_init__()

            # ---- start on the ground -----------------------------------------
            # z is an OFFSET from the default root height, so -0.45 puts the pelvis
            # near the floor. Full yaw, and roll/pitch wide enough to produce
            # face-down, back-down and side-down starts rather than one pose.
            # v1 started FULLY sprawled -- z -0.50..-0.40 with roll across the
            # whole circle -- and after 3000 iterations success_rate was 0.000 with
            # base_height -1.83, i.e. it never got off the ground. Prone-to-standing
            # is long-horizon and that start gives almost no gradient toward
            # standing.
            #
            # v2 spans the range instead: some episodes start nearly upright (a
            # stumble), some half-down, some fully prone. The easy ones bootstrap a
            # recovery behaviour that the hard ones can then extend -- a curriculum
            # by sampling rather than by scheduling, which needs no extra machinery.
            self.events.reset_base.params["pose_range"] = {
                "x": (-0.3, 0.3), "y": (-0.3, 0.3), "z": (-0.45, -0.05),
                "roll": (-1.8, 1.8), "pitch": (-1.0, 1.0), "yaw": (-3.14, 3.14),
            }
            self.events.reset_base.params["velocity_range"] = {
                "x": (0.0, 0.0), "y": (0.0, 0.0), "z": (0.0, 0.0),
                "roll": (0.0, 0.0), "pitch": (0.0, 0.0), "yaw": (0.0, 0.0),
            }
            # Sprawled limbs, not a tidy default pose.
            self.events.reset_robot_joints.params["position_range"] = (0.6, 1.4)

            # ---- being on the ground is the PREMISE, not a failure -----------
            self.terminations.base_contact = None

            # Long enough to actually complete a recovery.
            self.episode_length_s = 10.0

            # ---- nothing to track while lying down ---------------------------
            self.commands.base_velocity.ranges.lin_vel_x = (0.0, 0.0)
            self.commands.base_velocity.ranges.lin_vel_y = (0.0, 0.0)
            self.commands.base_velocity.ranges.ang_vel_z = (0.0, 0.0)
            self.rewards.track_lin_vel_xy_exp.weight = 0.0
            self.rewards.track_ang_vel_z_exp.weight = 0.0
            self.rewards.feet_air_time.weight = 0.0
            self.rewards.feet_slide.weight = 0.0
            self.rewards.termination_penalty.weight = 0.0

            # ---- stand up and stay level -------------------------------------
            # Uprightness carries more of the signal than height: standing tall
            # while face-down is not recovery, and orientation gives a gradient from
            # the very first frame whereas height does not.
            self.rewards.flat_orientation_l2.weight = -10.0
            self.rewards.base_height = RewTerm(
                func=mdp.base_height_l2,
                weight=-10.0,
                params={"target_height": STAND_HEIGHT,
                        "asset_cfg": SceneEntityCfg("robot")},
            )
            # Discourage thrashing: recovery should look like a push-up, not a
            # seizure. Slightly stronger than the locomotion defaults.
            self.rewards.action_rate_l2.weight = -0.01
            self.rewards.dof_torques_l2.weight = -1.0e-5

            # ---- on ice ------------------------------------------------------
            # Hands and feet need purchase to push against; 0.06 is what a limb
            # slides on. Spanning up to rock keeps it usable on mixed ground.
            self.events.physics_material.params["static_friction_range"] = (0.05, 1.0)
            self.events.physics_material.params["dynamic_friction_range"] = (0.04, 0.9)


    @configclass
    class G1GetupIceEnvCfg_PLAY(G1GetupIceEnvCfg):
        def __post_init__(self):
            super().__post_init__()
            self.scene.num_envs = 16
            self.observations.policy.enable_corruption = False
            self.events.push_robot = None
            self.events.base_external_force_torque = None
'''))

with open(G1DIR / "__init__.py", "a") as f:
    f.write(textwrap.dedent('''

        import gymnasium as gym  # noqa: E402
        from . import agents  # noqa: E402

        for _id, _cls in [("Isaac-Getup-G1-Ice-v0", "G1GetupIceEnvCfg"),
                          ("Isaac-Getup-G1-Ice-Play-v0", "G1GetupIceEnvCfg_PLAY")]:
            gym.register(
                id=_id,
                entry_point="isaaclab.envs:ManagerBasedRLEnv",
                disable_env_checker=True,
                kwargs={
                    "env_cfg_entry_point": f"{__name__}.getup_env_cfg:{_cls}",
                    "rsl_rl_cfg_entry_point":
                        f"{agents.__name__}.rsl_rl_ppo_cfg:G1FlatPPORunnerCfg",
                },
            )
    '''))

# This env changes more than any previous one -- termination removed, rewards
# rewritten, reset re-posed. Verify every piece before spending an hour of GPU.
VERIFY = textwrap.dedent(f'''
    import os, torch
    os.environ["OMNI_KIT_ACCEPT_EULA"] = "YES"
    os.environ.setdefault("HOME", "/root")
    from isaaclab.app import AppLauncher
    app = AppLauncher(headless=True, device="cuda:0").app
    import gymnasium as gym
    import isaaclab_tasks  # noqa
    from isaaclab_tasks.utils import parse_env_cfg
    cfg = parse_env_cfg("{TASK}", device="cuda:0", num_envs=64)
    print("base_contact termination:", cfg.terminations.base_contact, flush=True)
    print("episode_length_s        :", cfg.episode_length_s, flush=True)
    print("reset z range           :", cfg.events.reset_base.params["pose_range"]["z"],
          flush=True)
    print("base_height reward      :", cfg.rewards.base_height.weight, flush=True)
    print("friction                :",
          cfg.events.physics_material.params["static_friction_range"], flush=True)
    assert cfg.terminations.base_contact is None, "contact still terminates!"

    # The real check: do the robots actually START on the ground?
    env = gym.make("{TASK}", cfg=cfg)
    env.reset()
    h = env.unwrapped.scene["robot"].data.root_pos_w[:, 2]
    print(f"start pelvis height: mean {{h.mean():.3f}} min {{h.min():.3f}} "
          f"max {{h.max():.3f}}", flush=True)
    assert h.mean() < 0.60, f"robots are not starting fallen (mean {{h.mean():.3f}})"
    print("VERIFY_OK", flush=True)
    env.close(); app.close()
''')
pathlib.Path("verify.py").write_text(VERIFY)
if not sh(f"{PY} verify.py 2>&1 | grep -E 'termination|episode_length|reset z|base_height|"
          f"friction|start pelvis|VERIFY_OK|Error|assert' | tail -12", 900, "verify", tail=12):
    sys.exit("verification failed - not spending GPU time")

train_py = subprocess.run(f"find {LAB} -path '*rsl_rl*' -name train.py | head -1",
                          shell=True, capture_output=True, text=True).stdout.strip()
OUT.mkdir(parents=True, exist_ok=True)
sync = subprocess.Popen(
    f"while true; do sleep 180; cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; done", shell=True)

print("\n" + "=" * 60 + f"\nTRAINING FALL RECOVERY ON ICE  {MAX_ITER} iters\n" + "=" * 60,
      flush=True)
ok = sh(f"cd {LAB} && {PY} {train_py} --task {TASK} --headless "
        f"--num_envs {NUM_ENVS} --max_iterations {MAX_ITER} 2>&1 "
        "| grep -vE 'neuraylib|material_library|\\[Warning\\]' | tail -60",
        10800, "train", tail=60)

sync.terminate()
sh(f"cp -r {LAB}/logs/rsl_rl {OUT}/ 2>/dev/null; find {OUT} -name '*.pt' | tail -5",
   600, "final sync", tail=8)
print("\nGETUP TRAINING", "COMPLETE" if ok else "FAILED", flush=True)
